package exceptioncase.userdefineexception;

import java.util.Scanner;

public class CustomException {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Scanner scan=new Scanner(System.in);
		int num1, num2;
		System.out.println("Enter value");
		num1=scan.nextInt();
		num2=scan.nextInt();
		//long  rest=;
		//System.out.println(power(num1,num2));
		 
	}

}









